stages:
  - build
  - tests

build:
  stage: build
  image: beevelop/ionic:latest
  script:
    - rm -rf node_modules
    - npm install
    - ionic build
  artifacts:
    paths:
      - ./storage/logs
    expire_in: 15 days
    when: always

tests:
  stage: tests
  image: weboaks/node-karma-protractor-chrome:latest
  script:
    - rm -rf node_modules
    - npm install
    - npm run test
  artifacts:
    paths:
    - ./storage/logs
    expire_in: 15 days
    when: always
